builder:
  class: ScriptBuilder
  config:
    command: docker build --target production -t fml:<%= commit %> .
tester:
  class: ScriptTester
  config:
    command: docker build --target test -t fml:<%= commit %>-test .; docker-compose run -e VERSION=<%= commit %> test  
